//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Droid.scheduler.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Droid.scheduler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;notablesdays&gt;
        ///     &lt;notableday name=&quot;Independance&apos;s day&quot; openday=&quot;false&quot;&gt;
        ///         &lt;month&gt;8&lt;/month&gt;
        ///         &lt;day&gt;6&lt;/day&gt;
        ///         &lt;localname value=&quot;Independance&apos;s day&quot; /&gt;
        ///     &lt;/notableday&gt;  
        ///&lt;/notablesdays&gt;.
        /// </summary>
        public static string holidays_bolivia {
            get {
                return ResourceManager.GetString("holidays_bolivia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;notablesdays&gt;
        ///     &lt;notableday name=&quot;New year&apos;s day&quot; openday=&quot;false&quot;&gt;
        ///         &lt;month&gt;1&lt;/month&gt;
        ///         &lt;day&gt;1&lt;/day&gt;
        ///         &lt;localname value=&quot;Jour de l&apos;an&quot; /&gt;
        ///     &lt;/notableday&gt;
        ///     &lt;notableday name=&quot;Louis Riel Day&quot; openday=&quot;false&quot;&gt;
        ///         &lt;weekdayinmonth&gt;
        ///           &lt;month&gt;2&lt;/month&gt;
        ///           &lt;weekday&gt;1&lt;/weekday&gt;
        ///           &lt;weekdaynum&gt;3&lt;/weekdaynum&gt;
        ///         &lt;/weekdayinmonth&gt;
        ///         &lt;localname value=&quot;Louis Riel Day&quot; /&gt;
        ///         &lt;region value=&quot;MB&quot; /&gt;
        ///     &lt;/notableday&gt;
        ///     &lt;notableday name=&quot;Isla [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string holidays_canada {
            get {
                return ResourceManager.GetString("holidays_canada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;notablesdays&gt;
        ///  &lt;notableday name=&quot;New year&quot; openday=&quot;false&quot;&gt;
        ///    &lt;month&gt;1&lt;/month&gt;
        ///    &lt;day&gt;1&lt;/day&gt;
        ///    &lt;localname value=&quot;元旦&quot; /&gt;
        ///  &lt;/notableday&gt;
        ///  &lt;notableday name=&quot;Spring Festival&quot; openday=&quot;false&quot;&gt;
        ///    &lt;calendar&gt;hijri&lt;/calendar&gt;
        ///    &lt;month&gt;1&lt;/month&gt;
        ///    &lt;day&gt;1&lt;/day&gt;
        ///    &lt;localname value=&quot;春节&quot; /&gt;
        ///  &lt;/notableday&gt;
        ///  &lt;notableday name=&quot;Tomb-Sweeping Day&quot; openday=&quot;false&quot;&gt;
        ///	&lt;localname value=&quot;清明节&quot; /&gt;
        ///  &lt;/notableday&gt;
        ///  &lt;notableday name=&quot;Labour day&quot; openday=&quot;false&quot;&gt;
        ///	&lt;month&gt;5&lt;/month&gt;
        ///	&lt;day&gt;1&lt;/day&gt;
        ///	&lt;localname value=&quot; [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string holidays_china {
            get {
                return ResourceManager.GetString("holidays_china", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;notablesdays&gt;
        ///     &lt;notableday name=&quot;New year&apos;s day&quot; openday=&quot;false&quot;&gt;
        ///         &lt;month&gt;1&lt;/month&gt;
        ///         &lt;day&gt;1&lt;/day&gt;
        ///         &lt;localname value=&quot;Nouvel an&quot; /&gt;
        ///     &lt;/notableday&gt;
        ///     &lt;notableday name=&quot;Easter&quot; openday=&quot;false&quot;&gt;
        ///         &lt;easter /&gt;
        ///         &lt;localname value=&quot;Easter&quot; /&gt;
        ///     &lt;/notableday&gt;
        ///     &lt;notableday name=&quot;Easter Monday&quot; openday=&quot;false&quot;&gt;
        ///         &lt;daysafterholiday holiday=&quot;Easter&quot;&gt;
        ///             &lt;days&gt;1&lt;/days&gt;
        ///         &lt;/daysafterholiday&gt;
        ///         &lt;localname value=&quot;Lundi de Paques&quot; /&gt;
        ///     [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string holidays_france {
            get {
                return ResourceManager.GetString("holidays_france", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;notablesdays&gt;
        ///     &lt;notableday name=&quot;New year&apos;s day&quot; openday=&quot;false&quot;&gt;
        ///         &lt;month&gt;1&lt;/month&gt;
        ///         &lt;day&gt;1&lt;/day&gt;
        ///         &lt;localname value=&quot;Neujahrstag&quot; /&gt;
        ///     &lt;/notableday&gt;
        ///     &lt;notableday name=&quot;Épiphanie&quot; openday=&quot;false&quot;&gt;
        ///         &lt;month&gt;1&lt;/month&gt;
        ///         &lt;day&gt;6&lt;/day&gt;
        ///         &lt;localname value=&quot;Heilige Drei Könige&quot; /&gt;
        ///         &lt;region value=&quot;BW;BY;ST&quot; /&gt;
        ///     &lt;/notableday&gt;
        ///     &lt;notableday name=&quot;Easter&quot; openday=&quot;false&quot;&gt;
        ///         &lt;easter /&gt;
        ///         &lt;localname value=&quot;Easter&quot; /&gt;
        ///     &lt;/notableday&gt;
        /// [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string holidays_germany {
            get {
                return ResourceManager.GetString("holidays_germany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;notablesdays&gt;
        ///     &lt;notableday name=&quot;New year&apos;s day&quot; openday=&quot;false&quot;&gt;
        ///         &lt;month&gt;1&lt;/month&gt;
        ///         &lt;day&gt;1&lt;/day&gt;
        ///         &lt;localname value=&quot;Jour de l&apos;an&quot; /&gt;
        ///     &lt;/notableday&gt;  
        ///     &lt;notableday name=&quot;Labor&apos;s day&quot; openday=&quot;false&quot;&gt;
        ///         &lt;month&gt;5&lt;/month&gt;
        ///         &lt;day&gt;1&lt;/day&gt;
        ///         &lt;localname value=&quot;Fête du travail&quot; /&gt;
        ///     &lt;/notableday&gt;  
        ///     &lt;notableday name=&quot;Africa&apos;s day&quot; openday=&quot;false&quot;&gt;
        ///         &lt;month&gt;5&lt;/month&gt;
        ///         &lt;day&gt;25&lt;/day&gt;
        ///         &lt;localname value=&quot;Fête de l&apos;Afrique&quot; /&gt;
        ///     &lt;/ [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string holidays_guine {
            get {
                return ResourceManager.GetString("holidays_guine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;notablesdays&gt;
        ///     &lt;notableday name=&quot;Easter&quot; openday=&quot;false&quot;&gt;
        ///         &lt;easter /&gt;
        ///         &lt;localname value=&quot;Easter&quot; /&gt;
        ///     &lt;/notableday&gt;
        ///     &lt;notableday name=&quot;New year&apos;s day&quot; openday=&quot;false&quot;&gt;
        ///         &lt;calendar&gt;julian&lt;/calendar&gt;
        ///         &lt;month&gt;1&lt;/month&gt;
        ///         &lt;day&gt;1&lt;/day&gt;
        ///         &lt;localname value=&quot;New year&apos;s day&quot; /&gt;
        ///     &lt;/notableday&gt;
        ///     &lt;notableday name=&quot;Pongal&quot; openday=&quot;false&quot;&gt;
        ///         &lt;calendar&gt;julian&lt;/calendar&gt;
        ///         &lt;month&gt;1&lt;/month&gt;
        ///         &lt;day&gt;15&lt;/day&gt;
        ///         &lt;localname value=&quot;Makar [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string holidays_india {
            get {
                return ResourceManager.GetString("holidays_india", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;notablesdays&gt;
        ///     &lt;notableday name=&quot;Easter&quot;&gt;
        ///         &lt;Easter /&gt;
        ///     &lt;/notableday&gt;
        ///     &lt;notableday name=&quot;New year&apos;s day&quot; openday=&quot;false&quot;&gt;
        ///         &lt;month&gt;1&lt;/month&gt;
        ///         &lt;day&gt;1&lt;/day&gt;
        ///         &lt;localname value=&quot;Lá Caille&quot; /&gt;
        ///     &lt;/notableday&gt;
        ///     &lt;notableday name=&quot;Saint Patrick&apos;s Day&quot; openday=&quot;false&quot;&gt;
        ///         &lt;month&gt;3&lt;/month&gt;
        ///         &lt;day&gt;17&lt;/day&gt;
        ///         &lt;localname value=&quot;Lá Fhéile Pádraig&quot; /&gt;
        ///     &lt;/notableday&gt;
        ///     &lt;notableday name=&quot;Easter Monday&quot; openday=&quot;false&quot;&gt;
        ///         &lt;daysafterholiday ho [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string holidays_irland {
            get {
                return ResourceManager.GetString("holidays_irland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;notablesdays&gt;
        ///     &lt;notableday name=&quot;New year&apos;s day&quot; openday=&quot;false&quot;&gt;
        ///         &lt;month&gt;1&lt;/month&gt;
        ///         &lt;day&gt;1&lt;/day&gt;
        ///         &lt;localname value=&quot;Ganjitsu&quot; /&gt;
        ///     &lt;/notableday&gt;
        ///     &lt;notableday name=&quot;Majority accession&quot; openday=&quot;false&quot;&gt;
        ///         &lt;weekdayinmonth&gt;
        ///           &lt;month&gt;1&lt;/month&gt;
        ///           &lt;weekday&gt;1&lt;/weekday&gt;
        ///           &lt;weekdaynum&gt;2&lt;/weekdaynum&gt;
        ///         &lt;/weekdayinmonth&gt;
        ///         &lt;localname value=&quot;Seijin no Hi&quot; /&gt;
        ///     &lt;/notableday&gt;
        ///     &lt;notableday name=&quot;State fundation birthday&quot; openday=&quot;fa [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string holidays_japan {
            get {
                return ResourceManager.GetString("holidays_japan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;notablesdays&gt;
        ///     &lt;notableday name=&quot;New year&apos;s day&quot; openday=&quot;false&quot;&gt;
        ///         &lt;month&gt;1&lt;/month&gt;
        ///         &lt;day&gt;1&lt;/day&gt;
        ///         &lt;localname value=&quot;Jour de l&apos;an&quot; /&gt;
        ///     &lt;/notableday&gt;  
        ///     &lt;notableday name=&quot;Easter&quot; openday=&quot;false&quot;&gt;
        ///         &lt;easter /&gt;
        ///         &lt;localname value=&quot;Easter&quot; /&gt;
        ///     &lt;/notableday&gt;
        ///     &lt;notableday name=&quot;Easter Monday&quot; openday=&quot;false&quot;&gt;
        ///         &lt;daysafterholiday holiday=&quot;Easter&quot;&gt;
        ///             &lt;days&gt;1&lt;/days&gt;
        ///         &lt;/daysafterholiday&gt;
        ///         &lt;localname value=&quot;Lundi de Paques&quot; /&gt; [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string holidays_kenya {
            get {
                return ResourceManager.GetString("holidays_kenya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;notablesdays&gt;
        ///     &lt;notableday name=&quot;New year&apos;s day&quot; openday=&quot;false&quot;&gt;
        ///         &lt;month&gt;1&lt;/month&gt;
        ///         &lt;day&gt;1&lt;/day&gt;
        ///         &lt;localname value=&quot;Jour de l&apos;an&quot; /&gt;
        ///     &lt;/notableday&gt;
        ///     &lt;notableday name=&quot;Army&apos;s day&quot; openday=&quot;false&quot;&gt;
        ///         &lt;month&gt;1&lt;/month&gt;
        ///         &lt;day&gt;20&lt;/day&gt;
        ///         &lt;localname value=&quot;Fête de l&apos;armée&quot; /&gt;
        ///     &lt;/notableday&gt;
        ///     &lt;notableday name=&quot;Martyr&apos;s day&quot; openday=&quot;false&quot;&gt;
        ///         &lt;month&gt;3&lt;/month&gt;
        ///         &lt;day&gt;26&lt;/day&gt;
        ///         &lt;localname value=&quot;Journée des Martyrs&quot; /&gt;
        ///     &lt;/no [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string holidays_mali {
            get {
                return ResourceManager.GetString("holidays_mali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;notablesdays&gt;
        ///  &lt;notableday name=&quot;New year&apos;s day&quot; openday=&quot;false&quot;&gt;
        ///    &lt;month&gt;1&lt;/month&gt;
        ///    &lt;day&gt;1&lt;/day&gt;
        ///    &lt;localname value=&quot;Hari Tahun Baharu&quot; /&gt;
        ///	&lt;region value=&quot;kuala_lumpur;labuan_territory;malacca;negeri_sembilan;pahang;penang;perak;putrajaya;sabah;selangor;sarawak&quot; /&gt;
        ///  &lt;/notableday&gt;
        ///  &lt;notableday name=&quot;Federal Territory Day&quot; openday=&quot;false&quot;&gt;
        ///	&lt;month&gt;2&lt;/month&gt;
        ///	&lt;day&gt;1&lt;/day&gt;
        ///	&lt;localname value=&quot;Hari Wilayah&quot; /&gt;
        ///	&lt;region value=&quot;kuala_lumpur;labuan_territory;putrajaya&quot; /&gt;
        ///  &lt;/notableday&gt;
        ///  &lt;notableday n [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string holidays_malysia {
            get {
                return ResourceManager.GetString("holidays_malysia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;notablesdays&gt;
        ///  &lt;notableday name=&quot;New year&apos;s day&quot; openday=&quot;false&quot;&gt;
        ///    &lt;month&gt;1&lt;/month&gt;
        ///    &lt;day&gt;1&lt;/day&gt;
        ///    &lt;localname value=&quot;New Year&apos;s Day&quot; /&gt;
        ///  &lt;/notableday&gt;
        ///  &lt;notableday name=&quot;Day after New Year&apos;s Day&quot; openday=&quot;false&quot;&gt;
        ///    &lt;month&gt;1&lt;/month&gt;
        ///    &lt;day&gt;2&lt;/day&gt;
        ///    &lt;localname value=&quot;Day after New Year&apos;s Day&quot; /&gt;
        ///  &lt;/notableday&gt;
        ///  &lt;notableday name=&quot;Waitangi Day&quot; openday=&quot;false&quot;&gt;
        ///    &lt;month&gt;1&lt;/month&gt;
        ///    &lt;day&gt;6&lt;/day&gt;
        ///    &lt;localname value=&quot;Waitangi Day&quot; /&gt;
        ///  &lt;/notableday&gt;
        ///  &lt;notableday name=&quot;Easter&quot; openday=&quot; [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string holidays_new_zealand {
            get {
                return ResourceManager.GetString("holidays_new_zealand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;notablesdays&gt;
        ///     &lt;notableday name=&quot;Independance&apos;s Day&quot; openday=&quot;false&quot;&gt;
        ///         &lt;month&gt;8&lt;/month&gt;
        ///         &lt;day&gt;13&lt;/day&gt;
        ///         &lt;localname value=&quot;Fête de l&apos;Indépendance&quot; /&gt;
        ///     &lt;/notableday&gt;
        ///     &lt;notableday name=&quot;Nationnal&apos;s day&quot; openday=&quot;false&quot;&gt;
        ///         &lt;month&gt;12&lt;/month&gt;
        ///         &lt;day&gt;1&lt;/day&gt;
        ///         &lt;localname value=&quot;Fête nationale&quot; /&gt;
        ///     &lt;/notableday&gt;
        ///&lt;/notablesdays&gt;.
        /// </summary>
        public static string holidays_republique_centrafrique {
            get {
                return ResourceManager.GetString("holidays_republique_centrafrique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;notablesdays&gt;
        ///     &lt;notableday name=&quot;New year&apos;s day&quot; openday=&quot;false&quot;&gt;
        ///         &lt;month&gt;1&lt;/month&gt;
        ///         &lt;day&gt;1&lt;/day&gt;
        ///         &lt;localname value=&quot;Новый год&quot; /&gt;
        ///     &lt;/notableday&gt;
        ///     &lt;notableday name=&quot;Orthodoxe Chrismas day&quot; openday=&quot;false&quot;&gt;
        ///         &lt;month&gt;1&lt;/month&gt;
        ///         &lt;day&gt;7&lt;/day&gt;
        ///         &lt;localname value=&quot;Рождество Христово&quot; /&gt;
        ///     &lt;/notableday&gt;
        ///     &lt;notableday name=&quot;New old year&apos;s day&quot; openday=&quot;true&quot;&gt;
        ///         &lt;month&gt;1&lt;/month&gt;
        ///         &lt;day&gt;13&lt;/day&gt;
        ///         &lt;localname value=&quot;Старый новый год&quot; [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string holidays_russia {
            get {
                return ResourceManager.GetString("holidays_russia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;notablesdays&gt;
        ///     &lt;notableday name=&quot;New year&apos;s day&quot; openday=&quot;false&quot;&gt;
        ///         &lt;month&gt;1&lt;/month&gt;
        ///         &lt;day&gt;1&lt;/day&gt;
        ///         &lt;localname value=&quot;Jour de l&apos;an&quot; /&gt;
        ///     &lt;/notableday&gt;
        ///     &lt;notableday name=&quot;National liberation&quot; openday=&quot;false&quot;&gt;
        ///         &lt;month&gt;1&lt;/month&gt;
        ///         &lt;day&gt;13&lt;/day&gt;
        ///         &lt;localname value=&quot;Libération nationale&quot; /&gt;
        ///     &lt;/notableday&gt;
        ///     &lt;notableday name=&quot;Economic liberation&quot; openday=&quot;false&quot;&gt;
        ///         &lt;month&gt;1&lt;/month&gt;
        ///         &lt;day&gt;24&lt;/day&gt;
        ///         &lt;localname value=&quot;Libération é [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string holidays_togo {
            get {
                return ResourceManager.GetString("holidays_togo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;notablesdays&gt;
        ///  &lt;notableday name=&quot;New year&apos;s day&quot; openday=&quot;false&quot;&gt;
        ///    &lt;month&gt;1&lt;/month&gt;
        ///    &lt;day&gt;1&lt;/day&gt;
        ///    &lt;localname value=&quot;رأس العام	&quot; /&gt;
        ///  &lt;/notableday&gt;
        ///  &lt;notableday name=&quot;Revolution and Youth Day&quot; openday=&quot;false&quot;&gt;
        ///    &lt;month&gt;1&lt;/month&gt;
        ///    &lt;day&gt;14&lt;/day&gt;
        ///    &lt;localname value=&quot;عيد الثورة و الشباب&quot; /&gt;
        ///  &lt;/notableday&gt;
        ///  &lt;notableday name=&quot;Independence Day&quot; openday=&quot;false&quot;&gt;
        ///    &lt;month&gt;3&lt;/month&gt;
        ///    &lt;day&gt;20&lt;/day&gt;
        ///    &lt;localname value=&quot;عيد الإستقلال&quot; /&gt;
        ///  &lt;/notableday&gt;
        ///  &lt;notableday name=&quot;Martyrs&apos; Day&quot; opend [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string holidays_tunisie {
            get {
                return ResourceManager.GetString("holidays_tunisie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;notablesdays&gt;
        ///  &lt;notableday name=&quot;New year&quot; openday=&quot;false&quot;&gt;
        ///    &lt;month&gt;1&lt;/month&gt;
        ///    &lt;day&gt;1&lt;/day&gt;
        ///    &lt;localname value=&quot;Новий Рік&quot; /&gt;
        ///  &lt;/notableday&gt;
        ///  &lt;notableday name=&quot;Orthodox Christmas&quot; openday=&quot;false&quot;&gt;
        ///    &lt;month&gt;1&lt;/month&gt;
        ///    &lt;day&gt;7&lt;/day&gt;
        ///    &lt;localname value=&quot;Різдво&quot; /&gt;
        ///  &lt;/notableday&gt;
        ///  &lt;notableday name=&quot;International Women&apos;s Day&quot; openday=&quot;false&quot;&gt;
        ///    &lt;month&gt;3&lt;/month&gt;
        ///    &lt;day&gt;8&lt;/day&gt;
        ///	&lt;localname value=&quot;Міжнародний жіночий день&quot; /&gt;
        ///  &lt;/notableday&gt;
        ///  &lt;notableday name=&quot;Easter&quot; openday=&quot;false&quot;&gt;
        ///  	 &lt; [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string holidays_ukraine {
            get {
                return ResourceManager.GetString("holidays_ukraine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;notablesdays&gt;
        ///     &lt;notableday name=&quot;New year&apos;s day&quot; openday=&quot;false&quot;&gt;
        ///         &lt;month&gt;1&lt;/month&gt;
        ///         &lt;day&gt;1&lt;/day&gt;
        ///         &lt;localname value=&quot;New Year&apos;s Day&quot; /&gt;
        ///     &lt;/notableday&gt;
        ///     &lt;notableday name=&quot;New year&apos;s day after&quot; openday=&quot;false&quot;&gt;
        ///         &lt;month&gt;1&lt;/month&gt;
        ///         &lt;day&gt;2&lt;/day&gt;
        ///         &lt;localname value=&quot;New Year&apos;s Day after&quot; /&gt;
        ///         &lt;region value=&quot;EC&quot; /&gt;
        ///     &lt;/notableday&gt;
        ///     &lt;notableday name=&quot;Saint Patrick&apos;s Day&quot; openday=&quot;false&quot;&gt;
        ///         &lt;month&gt;3&lt;/month&gt;
        ///         &lt;day&gt;17&lt;/day&gt;
        ///       [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string holidays_united_kingdom {
            get {
                return ResourceManager.GetString("holidays_united_kingdom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;notablesdays&gt;
        ///     &lt;notableday name=&quot;New year&apos;s day&quot; openday=&quot;false&quot;&gt;
        ///         &lt;month&gt;1&lt;/month&gt;
        ///         &lt;day&gt;1&lt;/day&gt;
        ///         &lt;localname value=&quot;New year&apos;s day&quot; /&gt;
        ///           &lt;exceptions&gt;
        ///                &lt;day value=&quot;saturday&quot; day=&quot;-1&quot; /&gt;
        ///                &lt;day value=&quot;sunday&quot; day=&quot;1&quot; /&gt;
        ///           &lt;/exceptions&gt;
        ///     &lt;/notableday&gt;
        ///     &lt;notableday name=&quot;Chrismas day&quot; openday=&quot;false&quot;&gt;
        ///         &lt;month&gt;12&lt;/month&gt;
        ///         &lt;day&gt;25&lt;/day&gt;
        ///         &lt;localname value=&quot;Chrismas day&quot; /&gt;
        ///           &lt;exceptions&gt;
        ///           [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string holidays_united_state {
            get {
                return ResourceManager.GetString("holidays_united_state", resourceCulture);
            }
        }
    }
}
